# Site settings
title: Ansh Sarda
description:
#baseurl: "/blog" # the subpath of your site, e.g. /blog
#url: "ysarda.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ansh Sarda
user_description_theory:  Neuroscience enthusiast. Aspiring designer. Interested in working on cutting-edge solutions to any problem, learning and developing my skill set. Eagle Scout and EMT, always looking for a new challenge.
user_title: excuse the mess, it's a work in progress
email: anshsarda@outlook.com
#gplus_username:  lorem_ipsum


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
