# Site settings
title: Ansh Sarda
description:
#baseurl: "/blog" # the subpath of your site, e.g. /blog

# User settings
username: Ansh Sarda
user_description_theory: Hi! My name is Ansh, I'm an undergrad student at UCSD studying Cognitive and Behavioral Neuroscience. My future aspirations include a Master's degree in Data Science and a career in Computational Neuroscience. This website is a portfolio of my skill set in Python, R and SQL, demonstrated in the projects below. Thanks for checking it out!
user_title: excuse the mess, it's a work in progress
email: anshsarda@outlook.com
#gplus_username:  lorem_ipsum


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
